"""Derive an Agglomerated smoke-input registry from an existing ready registry."""

from __future__ import annotations

import argparse
import sys
from collections.abc import Mapping, Sequence
from copy import deepcopy
from pathlib import Path
from typing import Any

import yaml  # type: ignore[import-untyped]

MODEL_ID = "unet-agglomerated-specialized-v1"
OUTPUT_FILENAME = "registry-agglomerated-smoke-input.yaml"
_REQUIRED_ENTRY_FIELDS = (
    "adapter_path",
    "weight_path",
    "weight_sha256",
    "config_path",
    "model_card_path",
)
_SMOKE_GENERATED_ENTRY_FIELDS = {
    "adapter_sha256",
    "identity",
    "model_bundle",
    "model_bundle_id",
    "promotion_evidence",
    "provenance",
}
_SMOKE_GENERATED_METADATA_FIELDS = {
    "adapter_sha256",
    "config_sha256",
    "model_bundle_id",
    "model_card_sha256",
    "weight_sha256",
}


def prepare_smoke_registry(
    source_registry: Path,
    output_registry: Path,
    *,
    model_id: str = MODEL_ID,
) -> Path:
    source = source_registry.expanduser().resolve(strict=True)
    if not source.is_file():
        raise ValueError(f"source registry is not a file: {source}")
    output = output_registry.expanduser().resolve()
    if output.name != OUTPUT_FILENAME:
        raise ValueError(f"output registry filename must be {OUTPUT_FILENAME}")
    if output.parent != source.parent:
        raise ValueError(
            "output registry must be beside the source so relative asset paths remain valid"
        )
    if output.exists():
        raise ValueError(f"output registry already exists: {output}")

    try:
        payload = yaml.safe_load(source.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, yaml.YAMLError) as error:
        raise ValueError("source registry cannot be read") from error
    models = payload.get("models") if isinstance(payload, Mapping) else None
    if not isinstance(models, list):
        raise ValueError("source registry must contain a models list")
    matches = [
        entry
        for entry in models
        if isinstance(entry, Mapping)
        and isinstance(entry.get("metadata"), Mapping)
        and entry["metadata"].get("model_id") == model_id
    ]
    if len(matches) != 1:
        raise ValueError("source registry must contain exactly one Agglomerated model entry")

    entry: dict[str, Any] = deepcopy(dict(matches[0]))
    metadata = entry.get("metadata")
    if not isinstance(metadata, dict) or metadata.get("status") != "ready":
        raise ValueError("source Agglomerated model must have ready status")
    missing = [field for field in _REQUIRED_ENTRY_FIELDS if not entry.get(field)]
    if missing:
        raise ValueError(f"source Agglomerated model is missing required fields: {missing}")

    for field in _SMOKE_GENERATED_ENTRY_FIELDS:
        entry.pop(field, None)
    for field in _SMOKE_GENERATED_METADATA_FIELDS:
        metadata.pop(field, None)
    metadata.update(
        {
            "status": "unavailable",
            "health_error": "Agglomerated smoke has not run for this generated input registry.",
            "notes": "Automatically derived smoke input; readiness must be regenerated by smoke.",
        }
    )

    output_payload = {
        "schema_version": payload.get("schema_version", "2.0"),
        "models": [entry],
    }
    output.write_text(
        yaml.safe_dump(output_payload, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return output


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-registry", required=True, type=Path)
    parser.add_argument("--output-registry", required=True, type=Path)
    parser.add_argument("--model-id", default=MODEL_ID)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    namespace = build_parser().parse_args(argv)
    try:
        output = prepare_smoke_registry(
            namespace.source_registry,
            namespace.output_registry,
            model_id=namespace.model_id,
        )
    except (OSError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
