"""initial_schema

Revision ID: 53eaa43adc19
Revises:
Create Date: 2026-07-18 01:36:49.565373
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '53eaa43adc19'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_analysis_jobs'))
    )
    op.create_table('knowledge_documents',
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('doc_id', name=op.f('pk_knowledge_documents')),
    sa.UniqueConstraint('sha256', name=op.f('uq_knowledge_documents_sha256'))
    )
    op.create_table('model_registry',
    sa.Column('model_id', sa.String(length=160), nullable=False),
    sa.Column('family', sa.String(length=40), nullable=False),
    sa.Column('variant', sa.String(length=60), nullable=False),
    sa.Column('quality_tier', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('adapter', sa.String(length=500), nullable=False),
    sa.Column('weight_path', sa.Text(), nullable=True),
    sa.Column('config_path', sa.Text(), nullable=True),
    sa.Column('model_card_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('health_error', sa.Text(), nullable=True),
    sa.Column('weight_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('model_id', name=op.f('pk_model_registry'))
    )
    op.create_table('image_assets',
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bit_depth', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(length=120), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=True),
    sa.Column('material_formula', sa.String(length=255), nullable=True),
    sa.Column('experiment_conditions_json', sa.JSON(), nullable=False),
    sa.Column('analysis_roi_json', sa.JSON(), nullable=False),
    sa.Column('scale_nm_per_pixel', sa.Float(), nullable=True),
    sa.Column('box_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('bit_depth > 0', name=op.f('ck_image_assets_bit_depth_positive')),
    sa.CheckConstraint('height > 0', name=op.f('ck_image_assets_height_positive')),
    sa.CheckConstraint('scale_nm_per_pixel IS NULL OR scale_nm_per_pixel > 0', name=op.f('ck_image_assets_scale_positive_or_null')),
    sa.CheckConstraint('width > 0', name=op.f('ck_image_assets_width_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.job_id'], name=op.f('fk_image_assets_job_id_analysis_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', name=op.f('pk_image_assets')),
    sa.UniqueConstraint('job_id', 'filename', name='job_filename'),
    sa.UniqueConstraint('job_id', 'sha256', name='job_sha256')
    )
    op.create_index(op.f('ix_image_assets_job_id'), 'image_assets', ['job_id'], unique=False)
    op.create_index(op.f('ix_image_assets_sha256'), 'image_assets', ['sha256'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('chunk_id', sa.String(length=100), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('material_tags_json', sa.JSON(), nullable=False),
    sa.Column('vector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge_documents.doc_id'], name=op.f('fk_knowledge_chunks_doc_id_knowledge_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_knowledge_chunks')),
    sa.UniqueConstraint('vector_id', name=op.f('uq_knowledge_chunks_vector_id'))
    )
    op.create_index('ix_knowledge_chunks_doc_page', 'knowledge_chunks', ['doc_id', 'page_start'], unique=False)
    op.execute(
        """
        CREATE VIRTUAL TABLE knowledge_chunks_fts USING fts5(
            chunk_id UNINDEXED,
            text,
            section_title,
            material_tags
        )
        """
    )
    op.execute(
        """
        CREATE TRIGGER knowledge_chunks_fts_insert AFTER INSERT ON knowledge_chunks BEGIN
            INSERT INTO knowledge_chunks_fts(chunk_id, text, section_title, material_tags)
            VALUES (new.chunk_id, new.text, new.section_title, new.material_tags_json);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER knowledge_chunks_fts_delete AFTER DELETE ON knowledge_chunks BEGIN
            DELETE FROM knowledge_chunks_fts WHERE chunk_id = old.chunk_id;
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER knowledge_chunks_fts_update AFTER UPDATE ON knowledge_chunks BEGIN
            DELETE FROM knowledge_chunks_fts WHERE chunk_id = old.chunk_id;
            INSERT INTO knowledge_chunks_fts(chunk_id, text, section_title, material_tags)
            VALUES (new.chunk_id, new.text, new.section_title, new.material_tags_json);
        END
        """
    )
    op.create_table('query_logs',
    sa.Column('query_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('image_id', sa.String(length=64), nullable=True),
    sa.Column('query_type', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.image_id'], name=op.f('fk_query_logs_image_id_image_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.job_id'], name=op.f('fk_query_logs_job_id_analysis_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id', name=op.f('pk_query_logs'))
    )
    op.create_index(op.f('ix_query_logs_job_id'), 'query_logs', ['job_id'], unique=False)
    op.create_table('roi_boxes',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('box_id', sa.String(length=64), nullable=False),
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('x1', sa.Integer(), nullable=False),
    sa.Column('y1', sa.Integer(), nullable=False),
    sa.Column('x2', sa.Integer(), nullable=False),
    sa.Column('y2', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_roi_boxes_revision_positive')),
    sa.CheckConstraint('x1 < x2', name=op.f('ck_roi_boxes_x_ordered')),
    sa.CheckConstraint('x1 >= 0 AND y1 >= 0', name=op.f('ck_roi_boxes_origin_nonnegative')),
    sa.CheckConstraint('y1 < y2', name=op.f('ck_roi_boxes_y_ordered')),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.image_id'], name=op.f('fk_roi_boxes_image_id_image_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id', name=op.f('pk_roi_boxes')),
    sa.UniqueConstraint('image_id', 'revision', 'box_id', name='image_revision_box')
    )
    op.create_index('ix_roi_boxes_image_revision', 'roi_boxes', ['image_id', 'revision'], unique=False)
    op.create_table('segmentation_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=160), nullable=False),
    sa.Column('roi_mode', sa.String(length=40), nullable=False),
    sa.Column('box_revision', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('inference_json', sa.JSON(), nullable=False),
    sa.Column('run_config_json', sa.JSON(), nullable=False),
    sa.Column('paths_json', sa.JSON(), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('parent_run_id', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('runtime_ms IS NULL OR runtime_ms >= 0', name=op.f('ck_segmentation_runs_runtime_nonnegative')),
    sa.CheckConstraint('threshold IS NULL OR (threshold >= 0 AND threshold <= 1)', name=op.f('ck_segmentation_runs_threshold')),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.image_id'], name=op.f('fk_segmentation_runs_image_id_image_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.job_id'], name=op.f('fk_segmentation_runs_job_id_analysis_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.model_id'], name=op.f('fk_segmentation_runs_model_id_model_registry'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['segmentation_runs.run_id'], name=op.f('fk_segmentation_runs_parent_run_id_segmentation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_segmentation_runs'))
    )
    op.create_index('ix_segmentation_runs_job_status', 'segmentation_runs', ['job_id', 'status'], unique=False)
    op.create_table('image_summaries',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('particle_count', sa.Integer(), nullable=False),
    sa.Column('roi_area_px', sa.Integer(), nullable=False),
    sa.Column('number_density_px2', sa.Float(), nullable=False),
    sa.Column('number_density_um2', sa.Float(), nullable=True),
    sa.Column('mean_equivalent_diameter_px', sa.Float(), nullable=True),
    sa.Column('mean_equivalent_diameter_nm', sa.Float(), nullable=True),
    sa.Column('coverage_ratio', sa.Float(), nullable=False),
    sa.Column('perimeter_density_px', sa.Float(), nullable=False),
    sa.Column('perimeter_density_um', sa.Float(), nullable=True),
    sa.Column('quality_status', sa.String(length=40), nullable=False),
    sa.Column('quality_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('coverage_ratio >= 0 AND coverage_ratio <= 1', name=op.f('ck_image_summaries_coverage_ratio')),
    sa.CheckConstraint('particle_count >= 0', name=op.f('ck_image_summaries_particle_count_nonnegative')),
    sa.CheckConstraint('roi_area_px >= 0', name=op.f('ck_image_summaries_roi_area_nonnegative')),
    sa.ForeignKeyConstraint(['run_id'], ['segmentation_runs.run_id'], name=op.f('fk_image_summaries_run_id_segmentation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_image_summaries'))
    )
    op.create_table('particle_records',
    sa.Column('particle_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('instance_index', sa.Integer(), nullable=False),
    sa.Column('area_px', sa.Float(), nullable=False),
    sa.Column('perimeter_px', sa.Float(), nullable=False),
    sa.Column('equivalent_diameter_px', sa.Float(), nullable=False),
    sa.Column('equivalent_diameter_nm', sa.Float(), nullable=True),
    sa.Column('circularity', sa.Float(), nullable=True),
    sa.Column('bbox_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.CheckConstraint('area_px >= 0', name=op.f('ck_particle_records_area_nonnegative')),
    sa.CheckConstraint('instance_index >= 1', name=op.f('ck_particle_records_instance_index_positive')),
    sa.CheckConstraint('perimeter_px >= 0', name=op.f('ck_particle_records_perimeter_nonnegative')),
    sa.ForeignKeyConstraint(['run_id'], ['segmentation_runs.run_id'], name=op.f('fk_particle_records_run_id_segmentation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('particle_id', name=op.f('pk_particle_records')),
    sa.UniqueConstraint('run_id', 'instance_index', name='run_instance_index')
    )
    op.create_index(op.f('ix_particle_records_run_id'), 'particle_records', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_particle_records_run_id'), table_name='particle_records')
    op.drop_table('particle_records')
    op.drop_table('image_summaries')
    op.drop_index('ix_segmentation_runs_job_status', table_name='segmentation_runs')
    op.drop_table('segmentation_runs')
    op.drop_index('ix_roi_boxes_image_revision', table_name='roi_boxes')
    op.drop_table('roi_boxes')
    op.drop_index(op.f('ix_query_logs_job_id'), table_name='query_logs')
    op.drop_table('query_logs')
    op.execute("DROP TRIGGER IF EXISTS knowledge_chunks_fts_update")
    op.execute("DROP TRIGGER IF EXISTS knowledge_chunks_fts_delete")
    op.execute("DROP TRIGGER IF EXISTS knowledge_chunks_fts_insert")
    op.execute("DROP TABLE IF EXISTS knowledge_chunks_fts")
    op.drop_index('ix_knowledge_chunks_doc_page', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_image_assets_sha256'), table_name='image_assets')
    op.drop_index(op.f('ix_image_assets_job_id'), table_name='image_assets')
    op.drop_table('image_assets')
    op.drop_table('model_registry')
    op.drop_table('knowledge_documents')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
